-- COMPLETE DATABASE RECREATION SCRIPT
-- This script creates the entire database schema with all enhancements
-- Run this in NEON SQL Editor to create/recreate the complete database
-- Date: September 4, 2025
-- 
-- This combines all migrations:
-- - Category image URL support
-- - Shipping address and payment integration
-- - Order management enhancements
-- - Resource management system
-- - Staff assignment tracking
-- - All missing columns for API operations

-- ========================================
-- STEP 1: DROP EXISTING TABLES (OPTIONAL - UNCOMMENT IF RECREATING)
-- ========================================

-- Uncomment the following lines if you want to completely recreate the database
-- WARNING: This will delete all existing data!


DROP TABLE IF EXISTS staff_resource_assignment CASCADE;
DROP TABLE IF EXISTS usage_history CASCADE;
DROP TABLE IF EXISTS notification CASCADE;
DROP TABLE IF EXISTS staff_types CASCADE;
DROP TABLE IF EXISTS resource_types CASCADE;
DROP TABLE IF EXISTS supplier_order CASCADE;
DROP TABLE IF EXISTS supplier_item CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS order_item CASCADE;
DROP TABLE IF EXISTS customer_order CASCADE;
DROP TABLE IF EXISTS resource CASCADE;
DROP TABLE IF EXISTS staff CASCADE;
DROP TABLE IF EXISTS inventory_item CASCADE;
DROP TABLE IF EXISTS supplier CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS owner CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

-- Drop views
DROP VIEW IF EXISTS resource_with_assignment_view CASCADE;
DROP VIEW IF EXISTS order_summary_view CASCADE;
DROP VIEW IF EXISTS customer_order_history_view CASCADE;

-- Drop enum types
DROP TYPE IF EXISTS user_role_type CASCADE;
DROP TYPE IF EXISTS account_status CASCADE;
DROP TYPE IF EXISTS branch_status CASCADE;
DROP TYPE IF EXISTS order_status CASCADE;
DROP TYPE IF EXISTS payment_status CASCADE;
DROP TYPE IF EXISTS availability_status CASCADE;

-- Drop functions
DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;



-- ========================================
-- STEP 2: CREATE ENUM TYPES
-- ========================================

-- Create all required enum types
DO $$ BEGIN
    CREATE TYPE user_role_type AS ENUM ('OWNER', 'BRANCH_MANAGER', 'STAFF', 'SUPPLIER', 'CUSTOMER');
EXCEPTION
    WHEN duplicate_object THEN null;
END 
$$ LANGUAGE plpgsql;

DO $$ BEGIN
    CREATE TYPE account_status AS ENUM ('active', 'inactive', 'suspended', 'pending_activation');
EXCEPTION
    WHEN duplicate_object THEN null;
END 
$$ LANGUAGE plpgsql;

DO $$ BEGIN
    CREATE TYPE order_status AS ENUM ('pending', 'processing', 'completed', 'cancelled');
EXCEPTION
    WHEN duplicate_object THEN null;
END
$$ LANGUAGE plpgsql;

DO $$ BEGIN
    CREATE TYPE payment_status AS ENUM ('paid', 'unpaid', 'refunded', 'failed');
EXCEPTION
    WHEN duplicate_object THEN null;
END
$$ LANGUAGE plpgsql;

DO $$ BEGIN
    CREATE TYPE availability_status AS ENUM ('available', 'under_maintenance', 'used');
EXCEPTION
    WHEN duplicate_object THEN null;
END
$$ LANGUAGE plpgsql;

-- ========================================
-- STEP 3: CREATE CORE TABLES
-- ========================================

-- 1. Roles table
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(255) UNIQUE NOT NULL,
    description VARCHAR(255)
);

-- 2. User table (with all enhancements)
CREATE TABLE IF NOT EXISTS app_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    last_login TIMESTAMP WITH TIME ZONE,
    profile_pic_url VARCHAR(255),
    account_status VARCHAR(255) NOT NULL DEFAULT 'active',
    role_id BIGINT NOT NULL,
    created_by BIGINT,
    password_hash VARCHAR(255),
    temp_password BOOLEAN DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT user_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT,
    CONSTRAINT user_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_user(user_id) ON DELETE SET NULL
);

-- 3. Branches table
CREATE TABLE IF NOT EXISTS branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_number VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    description VARCHAR(255),
    location VARCHAR(255),
    name VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    manager_id BIGINT,
    owner_id BIGINT,
    CONSTRAINT fk6eeprxgcycf33592pdt128nbq FOREIGN KEY (manager_id) REFERENCES app_user(user_id),
    CONSTRAINT fkaemly69tetshuf108yk7ijmvg FOREIGN KEY (owner_id) REFERENCES app_user(user_id)
);


-- 4. Category table (with image URL support)
CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT UNIQUE NOT NULL,
    category_img_url VARCHAR(500)
);

-- 5. Customer table (with all customer creation fields)
CREATE TABLE IF NOT EXISTS customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    customer_name TEXT NOT NULL,
    customer_tel VARCHAR(20),
    address TEXT,
    loyalty_points NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    customer_email TEXT,
    CONSTRAINT customer_loyalty_points_check CHECK (loyalty_points >= 0::numeric),
    CONSTRAINT customer_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE SET NULL
);

-- 6. Inventory item table (with image URL support)
CREATE TABLE IF NOT EXISTS inventory_item (
    inventory_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    category_id BIGINT NOT NULL,
    low_stock_threshold INTEGER NOT NULL DEFAULT 0,
    unit_price NUMERIC(12,2) NOT NULL,
    branch_id BIGINT NOT NULL,
    image_url VARCHAR(500),
    CONSTRAINT inventory_item_low_stock_threshold_check CHECK (low_stock_threshold >= 0),
    CONSTRAINT inventory_item_quantity_check CHECK (quantity >= 0),
    CONSTRAINT inventory_item_unit_price_check CHECK (unit_price >= 0::numeric),
    CONSTRAINT inventory_item_category_id_fkey FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE RESTRICT,
    CONSTRAINT inventory_item_branch_id_inventory_name_key UNIQUE (branch_id, inventory_name)
);

-- 7. Staff table (with proper array type and all fields)
CREATE TABLE IF NOT EXISTS staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    address VARCHAR(255),
    tel VARCHAR(255),
    branch_id BIGINT,
    manager_id BIGINT,
    salary NUMERIC(38,2),
    staff_types TEXT[] NOT NULL DEFAULT '{}',
    hire_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    is_active BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT staff_salary_check CHECK (salary >= 0::numeric),
    CONSTRAINT fk1lha0ag3td43wl4slo0mnujdq FOREIGN KEY (branch_id) REFERENCES branches(id),
    CONSTRAINT staff_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES app_user(user_id) ON DELETE SET NULL,
    CONSTRAINT staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE CASCADE
);

-- 8. Resource table (with full resource management features)
CREATE TABLE IF NOT EXISTS resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    resource_number TEXT NOT NULL,
    description TEXT,
    resource_type VARCHAR(100) DEFAULT 'GENERAL',
    availability_status availability_status NOT NULL DEFAULT 'available',
    branch_id BIGINT NOT NULL,
    current_assignee_id BIGINT,
    assigned_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    created_by BIGINT,
    CONSTRAINT resource_current_assignee_id_fkey FOREIGN KEY (current_assignee_id) REFERENCES staff(id) ON DELETE SET NULL,
    CONSTRAINT resource_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_user(user_id) ON DELETE SET NULL,
    CONSTRAINT resource_branch_id_resource_number_key UNIQUE (branch_id, resource_number)
);

-- 9. Customer order table (with shipping address and payment integration)
CREATE TABLE IF NOT EXISTS customer_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    order_status order_status NOT NULL DEFAULT 'pending',
    total_amount NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    payment_status payment_status NOT NULL DEFAULT 'unpaid',
    branch_id BIGINT,
    shipping_address TEXT,
    stripe_payment_intent_id VARCHAR(255),
    notes TEXT,
    CONSTRAINT customer_order_total_amount_check CHECK (total_amount >= 0::numeric),
    CONSTRAINT customer_order_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE SET NULL
);

-- 10. Order item table (with unit price and total price)
CREATE TABLE IF NOT EXISTS order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    inventory_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    CONSTRAINT order_item_quantity_check CHECK (quantity > 0),
    CONSTRAINT order_item_unit_price_check CHECK (unit_price >= 0::numeric),
    CONSTRAINT order_item_total_price_check CHECK (total_price >= 0::numeric),
    CONSTRAINT order_item_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES inventory_item(inventory_id) ON DELETE RESTRICT,
    CONSTRAINT order_item_order_id_fkey FOREIGN KEY (order_id) REFERENCES customer_order(id) ON DELETE CASCADE
);

-- 11. Owner table
CREATE TABLE IF NOT EXISTS owner (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT owner_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE CASCADE
);

-- 12. Payment table (with Stripe integration)
CREATE TABLE IF NOT EXISTS payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    payment_method VARCHAR(50) DEFAULT 'stripe',
    stripe_payment_intent_id VARCHAR(255),
    stripe_charge_id VARCHAR(255),
    payment_status payment_status NOT NULL DEFAULT 'unpaid',
    processed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    metadata JSONB,
    transaction_id TEXT UNIQUE,
    CONSTRAINT payment_amount_check CHECK (amount >= 0::numeric),
    CONSTRAINT payment_order_id_fkey FOREIGN KEY (order_id) REFERENCES customer_order(id) ON DELETE CASCADE
);

-- 13. Supplier table
CREATE TABLE IF NOT EXISTS supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    supplier_name TEXT NOT NULL,
    supplier_tel TEXT,
    address TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    supplier_email TEXT,
    CONSTRAINT supplier_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE SET NULL
);

-- 14. Supplier item table
CREATE TABLE IF NOT EXISTS supplier_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    item_name TEXT NOT NULL,
    CONSTRAINT supplier_item_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE CASCADE,
    CONSTRAINT supplier_item_supplier_id_item_name_key UNIQUE (supplier_id, item_name)
);

-- 15. Supplier order table
CREATE TABLE IF NOT EXISTS supplier_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT,
    order_status order_status NOT NULL DEFAULT 'pending',
    quantity NUMERIC(12,2) NOT NULL,
    item_price NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    branch_id BIGINT,
    CONSTRAINT supplier_order_item_price_check CHECK (item_price >= 0::numeric),
    CONSTRAINT supplier_order_quantity_check CHECK (quantity > 0::numeric),
    CONSTRAINT supplier_order_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE SET NULL
);

-- 16. Usage history table
CREATE TABLE IF NOT EXISTS usage_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE,
    purpose TEXT,
    resource_id BIGINT NOT NULL,
    CONSTRAINT usage_history_check CHECK ((end_date IS NULL) OR (end_date >= start_date)),
    CONSTRAINT usage_history_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES resource(id) ON DELETE CASCADE
);

-- 17. Notification table
CREATE TABLE IF NOT EXISTS notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT notification_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE CASCADE
);

-- 18. Staff resource assignment table (with full assignment tracking)
CREATE TABLE IF NOT EXISTS staff_resource_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    assigned_by BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    purpose TEXT,
    start_date DATE,
    end_date DATE,
    start_time TIME,
    end_time TIME,
    unassigned_at TIMESTAMP WITH TIME ZONE,
    unassigned_by BIGINT,
    CONSTRAINT staff_resource_assignment_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES app_user(user_id) ON DELETE SET NULL,
    CONSTRAINT staff_resource_assignment_unassigned_by_fkey FOREIGN KEY (unassigned_by) REFERENCES app_user(user_id) ON DELETE SET NULL,
    CONSTRAINT staff_resource_assignment_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES resource(id) ON DELETE CASCADE,
    CONSTRAINT staff_resource_assignment_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE,
    CONSTRAINT staff_resource_assignment_staff_id_resource_id_key UNIQUE (staff_id, resource_id)
);

-- 19. Staff types table (legacy compatibility)
CREATE TABLE IF NOT EXISTS staff_types (
    staff_id BIGINT NOT NULL,
    staff_type VARCHAR(255),
    CONSTRAINT staff_types_staff_type_check CHECK (staff_type::text = ANY (ARRAY['INVENTORY'::character varying, 'SALES'::character varying, 'RESOURCES'::character varying]::text[])),
    CONSTRAINT fke35o60bickknpq1r0y9ddnwy3 FOREIGN KEY (staff_id) REFERENCES staff(id)
);

-- 20. Resource types table
CREATE TABLE IF NOT EXISTS resource_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- ========================================
-- STEP 4: CREATE FUNCTIONS AND TRIGGERS
-- ========================================

-- Function for updating timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger for customer_order table
DROP TRIGGER IF EXISTS update_customer_order_updated_at ON customer_order;
CREATE TRIGGER update_customer_order_updated_at
    BEFORE UPDATE ON customer_order
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Trigger for resource table
DROP TRIGGER IF EXISTS update_resource_updated_at ON resource;
CREATE TRIGGER update_resource_updated_at
    BEFORE UPDATE ON resource
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ========================================
-- STEP 5: CREATE INDEXES FOR PERFORMANCE
-- ========================================

-- User and authentication indexes
CREATE INDEX IF NOT EXISTS idx_user_firebase_uid ON app_user(firebase_uid);
CREATE INDEX IF NOT EXISTS idx_user_email ON app_user(email);
CREATE INDEX IF NOT EXISTS idx_user_role_id ON app_user(role_id);
CREATE INDEX IF NOT EXISTS idx_user_is_active ON app_user(is_active);

-- Customer order and payment indexes
CREATE INDEX IF NOT EXISTS idx_customer_order_customer_id ON customer_order(customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_order_status ON customer_order(order_status);
CREATE INDEX IF NOT EXISTS idx_customer_order_payment_status ON customer_order(payment_status);
CREATE INDEX IF NOT EXISTS idx_customer_order_stripe_intent ON customer_order(stripe_payment_intent_id);
CREATE INDEX IF NOT EXISTS idx_customer_order_created_at ON customer_order(created_at);

-- Order item indexes
CREATE INDEX IF NOT EXISTS idx_order_item_order_id ON order_item(order_id);
CREATE INDEX IF NOT EXISTS idx_order_item_inventory_id ON order_item(inventory_id);

-- Payment indexes
CREATE INDEX IF NOT EXISTS idx_payment_order_id ON payment(order_id);
CREATE INDEX IF NOT EXISTS idx_payment_stripe_intent ON payment(stripe_payment_intent_id);
CREATE INDEX IF NOT EXISTS idx_payment_status ON payment(payment_status);

-- Inventory and category indexes
CREATE INDEX IF NOT EXISTS idx_inventory_item_category_id ON inventory_item(category_id);
CREATE INDEX IF NOT EXISTS idx_inventory_item_branch_id ON inventory_item(branch_id);
CREATE INDEX IF NOT EXISTS idx_inventory_item_has_image ON inventory_item(image_url) WHERE image_url IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_category_has_image ON category(category_img_url) WHERE category_img_url IS NOT NULL;

-- Staff and resource indexes
CREATE INDEX IF NOT EXISTS idx_staff_user_id ON staff(user_id);
CREATE INDEX IF NOT EXISTS idx_staff_manager_id ON staff(manager_id);
CREATE INDEX IF NOT EXISTS idx_staff_branch_id ON staff(branch_id);
CREATE INDEX IF NOT EXISTS idx_staff_is_active ON staff(is_active);

-- Resource management indexes
CREATE INDEX IF NOT EXISTS idx_resource_branch_id ON resource(branch_id);
CREATE INDEX IF NOT EXISTS idx_resource_availability_status ON resource(availability_status);
CREATE INDEX IF NOT EXISTS idx_resource_type ON resource(resource_type);
CREATE INDEX IF NOT EXISTS idx_resource_current_assignee ON resource(current_assignee_id);

-- Staff resource assignment indexes
CREATE INDEX IF NOT EXISTS idx_staff_resource_assignment_staff_id ON staff_resource_assignment(staff_id);
CREATE INDEX IF NOT EXISTS idx_staff_resource_assignment_resource_id ON staff_resource_assignment(resource_id);
CREATE INDEX IF NOT EXISTS idx_staff_resource_assignment_active ON staff_resource_assignment(is_active);
CREATE INDEX IF NOT EXISTS idx_staff_resource_assignment_dates ON staff_resource_assignment(start_date, end_date);

-- Customer and supplier indexes
CREATE INDEX IF NOT EXISTS idx_customer_user_id ON customer(user_id);
CREATE INDEX IF NOT EXISTS idx_customer_email ON customer(customer_email);
CREATE INDEX IF NOT EXISTS idx_supplier_user_id ON supplier(user_id);

-- ========================================
-- STEP 6: CREATE VIEWS
-- ========================================

-- Order summary view with customer and item details
CREATE OR REPLACE VIEW order_summary_view AS
SELECT 
    co.id as order_id,
    co.total_amount,
    co.order_status,
    co.payment_status,
    co.created_at as order_date,
    co.shipping_address,
    co.stripe_payment_intent_id,
    c.customer_name,
    c.customer_email,
    COUNT(oi.id) as item_count,
    STRING_AGG(ii.inventory_name, ', ') as items
FROM customer_order co
LEFT JOIN customer c ON co.customer_id = c.id
LEFT JOIN order_item oi ON co.id = oi.order_id
LEFT JOIN inventory_item ii ON oi.inventory_id = ii.inventory_id
GROUP BY co.id, co.total_amount, co.order_status, co.payment_status, co.created_at, co.shipping_address, co.stripe_payment_intent_id, c.customer_name, c.customer_email;

-- Customer order history view
CREATE OR REPLACE VIEW customer_order_history_view AS
SELECT 
    c.id as customer_id,
    c.customer_name,
    c.customer_email,
    co.id as order_id,
    co.total_amount,
    co.order_status,
    co.payment_status,
    co.created_at as order_date,
    COUNT(oi.id) as items_count
FROM customer c
LEFT JOIN customer_order co ON c.id = co.customer_id
LEFT JOIN order_item oi ON co.id = oi.order_id
GROUP BY c.id, c.customer_name, c.customer_email, co.id, co.total_amount, co.order_status, co.payment_status, co.created_at
ORDER BY co.created_at DESC;

-- Resource with assignment view
CREATE OR REPLACE VIEW resource_with_assignment_view AS
SELECT 
    r.id,
    r.name,
    r.resource_number,
    r.description,
    r.resource_type,
    r.availability_status,
    r.branch_id,
    r.created_at,
    r.updated_at,
    r.created_by,
    
    -- Current assignment details
    sra.id as assignment_id,
    sra.purpose,
    sra.start_date,
    sra.end_date,
    sra.start_time,
    sra.end_time,
    sra.assigned_at,
    
    -- Staff details
    s.id as staff_id,
    s.first_name,
    s.last_name,
    s.email as staff_email,
    s.tel as staff_phone,
    
    -- Branch details
    b.name as branch_name,
    b.location as branch_location
    
FROM resource r
LEFT JOIN staff_resource_assignment sra ON r.id = sra.resource_id AND sra.is_active = true
LEFT JOIN staff s ON sra.staff_id = s.id
LEFT JOIN branches b ON r.branch_id = b.id;

-- ========================================
-- STEP 7: INSERT DEFAULT DATA
-- ========================================

-- Insert default roles
INSERT INTO roles (role, description) VALUES 
('OWNER', 'System administrator with full access'),
('BRANCH_MANAGER', 'Manager of a specific branch'),
('STAFF', 'Branch staff member'),
('SUPPLIER', 'External supplier'),
('CUSTOMER', 'Customer of the business')
ON CONFLICT (role) DO NOTHING;


-- Insert default resource types
INSERT INTO resource_types (name, description) VALUES 
('VEHICLE', 'Delivery trucks, vans, cars, and other vehicles'),
('EQUIPMENT', 'Forklifts, machinery, and tools'),
('FACILITY', 'Warehouses, meeting rooms, and spaces'),
('TECHNOLOGY', 'Computers, tablets, and IT equipment'),
('GENERAL', 'Other miscellaneous resources')
ON CONFLICT (name) DO NOTHING;

-- Insert default categories
INSERT INTO category (category_name) VALUES 
('Electronics'),
('Clothing'),
('Food & Beverages'),
('Home & Garden'),
('Sports & Outdoors')
ON CONFLICT (category_name) DO NOTHING;

-- ========================================
-- STEP 8: ADD COLUMN COMMENTS
-- ========================================

-- Table comments
COMMENT ON TABLE customer_order IS 'Customer orders with shipping address and Stripe payment integration';
COMMENT ON TABLE order_item IS 'Individual items within customer orders with pricing details';
COMMENT ON TABLE payment IS 'Payment records linked to orders with Stripe integration';
COMMENT ON TABLE resource IS 'Company resources including vehicles, equipment, and facilities';
COMMENT ON TABLE staff_resource_assignment IS 'Tracks current and historical assignments of resources to staff';

-- Column comments
COMMENT ON COLUMN category.category_img_url IS 'URL or path to the category image (optional)';
COMMENT ON COLUMN inventory_item.image_url IS 'URL or path to the inventory item image (optional)';
COMMENT ON COLUMN customer_order.shipping_address IS 'Customer shipping address for order delivery';
COMMENT ON COLUMN customer_order.stripe_payment_intent_id IS 'Stripe Payment Intent ID for tracking payments';
COMMENT ON COLUMN customer_order.updated_at IS 'Timestamp when the order was last updated (used by webhooks)';
COMMENT ON COLUMN order_item.unit_price IS 'Price per unit at time of order';
COMMENT ON COLUMN order_item.total_price IS 'Total price for this line item (quantity * unit_price)';
COMMENT ON COLUMN customer.customer_tel IS 'Customer phone number (optional)';
COMMENT ON COLUMN app_user.is_active IS 'Whether the user account is active';
COMMENT ON COLUMN staff.staff_types IS 'Array of staff type permissions: SALES, INVENTORY, RESOURCES';
COMMENT ON COLUMN resource.description IS 'Detailed description of the resource';
COMMENT ON COLUMN resource.resource_type IS 'Category of resource: VEHICLE, EQUIPMENT, FACILITY, TECHNOLOGY, GENERAL';
COMMENT ON COLUMN payment.stripe_payment_intent_id IS 'Stripe Payment Intent ID';
COMMENT ON COLUMN payment.stripe_charge_id IS 'Stripe Charge ID when payment is completed';
COMMENT ON COLUMN payment.metadata IS 'Additional payment metadata in JSON format';

-- View comments
COMMENT ON VIEW order_summary_view IS 'Consolidated view of orders with customer and item details';
COMMENT ON VIEW customer_order_history_view IS 'Customer order history with item counts';
COMMENT ON VIEW resource_with_assignment_view IS 'Resources with their current assignment and staff details';

-- ========================================
-- STEP 9: VERIFICATION AND SUCCESS MESSAGE
-- ========================================

-- Verify the migration completed successfully
SELECT 'DATABASE RECREATION COMPLETED SUCCESSFULLY!' AS status;

-- Show table counts
SELECT 
    table_name,
    COUNT(*) as column_count
FROM information_schema.columns 
WHERE table_name IN (
    'roles', 'user', 'branches', 'category', 'customer', 'inventory_item', 
    'staff', 'resource', 'customer_order', 'order_item', 'payment', 
    'supplier', 'supplier_item', 'supplier_order', 'owner', 'notification',
    'usage_history', 'staff_resource_assignment', 'staff_types', 'resource_types'
)
GROUP BY table_name
ORDER BY table_name;

-- Show default data counts
SELECT 'DEFAULT DATA INSERTED:' AS section;
SELECT 'roles' as table_name, COUNT(*) as record_count FROM roles
UNION ALL
SELECT 'branches' as table_name, COUNT(*) as record_count FROM branches
UNION ALL
SELECT 'resource_types' as table_name, COUNT(*) as record_count FROM resource_types
UNION ALL
SELECT 'category' as table_name, COUNT(*) as record_count FROM category;

-- Show key enhancements
SELECT 'KEY ENHANCEMENTS INCLUDED:' AS enhancements;
SELECT '✅ Category image URL support' AS feature
UNION ALL SELECT '✅ Inventory item image URLs' AS feature
UNION ALL SELECT '✅ Shipping address in orders' AS feature  
UNION ALL SELECT '✅ Stripe payment integration' AS feature
UNION ALL SELECT '✅ Order item pricing (unit_price, total_price)' AS feature
UNION ALL SELECT '✅ Customer phone number support' AS feature
UNION ALL SELECT '✅ User active status tracking' AS feature
UNION ALL SELECT '✅ Resource management system' AS feature
UNION ALL SELECT '✅ Staff resource assignment tracking' AS feature
UNION ALL SELECT '✅ Comprehensive indexing for performance' AS feature
UNION ALL SELECT '✅ Helpful views for order/resource management' AS feature;

-- Final success message
SELECT 'Your complete database has been created with all enhancements!' AS final_message;
SELECT 'All API endpoints should now work without missing column errors.' AS next_steps;