-- Complete Database Schema based on working database
-- Run this to create the exact same structure

-- First, ensure we have all the required enum types
DO $$ BEGIN
    CREATE TYPE user_role_type AS ENUM ('OWNER', 'BRANCH_MANAGER', 'STAFF', 'SUPPLIER', 'CUSTOMER');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE account_status AS ENUM ('active', 'inactive', 'suspended', 'pending_activation');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE branch_status AS ENUM ('active', 'inactive');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE order_status AS ENUM ('pending', 'processing', 'completed', 'cancelled');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE payment_status AS ENUM ('paid', 'unpaid');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE availability_status AS ENUM ('available', 'under_maintenance', 'used');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create tables in dependency order

-- 1. Roles table (exactly as shown in working DB)
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(255) UNIQUE NOT NULL,
    description VARCHAR(255)
);

-- 2. User table
CREATE TABLE IF NOT EXISTS "user" (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    last_login TIMESTAMP WITH TIME ZONE,
    profile_pic_url VARCHAR(255),
    account_status VARCHAR(255) NOT NULL DEFAULT 'active',
    role_id BIGINT NOT NULL,
    created_by BIGINT,
    password_hash VARCHAR(255),
    temp_password BOOLEAN DEFAULT false,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT user_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT,
    CONSTRAINT user_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(user_id) ON DELETE SET NULL
);

-- 3. Branches table
CREATE TABLE IF NOT EXISTS branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_number VARCHAR(255),
    created_at TIMESTAMP,
    description VARCHAR(255),
    location VARCHAR(255),
    name VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(255),
    manager_id BIGINT,
    owner_id BIGINT,
    CONSTRAINT branches_status_check CHECK (status::text = ANY (ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying]::text[])),
    CONSTRAINT fk6eeprxgcycf33592pdt128nbq FOREIGN KEY (manager_id) REFERENCES "user"(user_id),
    CONSTRAINT fkaemly69tetshuf108yk7ijmvg FOREIGN KEY (owner_id) REFERENCES "user"(user_id)
);

-- 4. Category table
CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT UNIQUE NOT NULL
);

-- 5. Customer table
CREATE TABLE IF NOT EXISTS customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    customer_name TEXT NOT NULL,
    customer_tel TEXT,
    address TEXT,
    loyalty_points NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    customer_email TEXT,
    CONSTRAINT customer_loyalty_points_check CHECK (loyalty_points >= 0::numeric),
    CONSTRAINT customer_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE SET NULL
);

-- 6. Inventory item table
CREATE TABLE IF NOT EXISTS inventory_item (
    inventory_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    category_id BIGINT NOT NULL,
    low_stock_threshold INTEGER NOT NULL DEFAULT 0,
    unit_price NUMERIC(12,2) NOT NULL,
    branch_id BIGINT NOT NULL,
    CONSTRAINT inventory_item_low_stock_threshold_check CHECK (low_stock_threshold >= 0),
    CONSTRAINT inventory_item_quantity_check CHECK (quantity >= 0),
    CONSTRAINT inventory_item_unit_price_check CHECK (unit_price >= 0::numeric),
    CONSTRAINT inventory_item_category_id_fkey FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE RESTRICT,
    CONSTRAINT inventory_item_branch_id_inventory_name_key UNIQUE (branch_id, inventory_name)
);

-- 7. Staff table
CREATE TABLE IF NOT EXISTS staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    address VARCHAR(255),
    tel VARCHAR(255),
    branch_id BIGINT,
    manager_id BIGINT,
    salary NUMERIC(38,2),
    staff_types TEXT NOT NULL DEFAULT '{}',
    hire_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    is_active BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT staff_salary_check CHECK (salary >= 0::numeric),
    CONSTRAINT fk1lha0ag3td43wl4slo0mnujdq FOREIGN KEY (branch_id) REFERENCES branches(id),
    CONSTRAINT staff_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES "user"(user_id) ON DELETE SET NULL,
    CONSTRAINT staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE
);

-- 8. Resource table
CREATE TABLE IF NOT EXISTS resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    resource_number TEXT NOT NULL,
    availability_status availability_status NOT NULL DEFAULT 'available',
    branch_id BIGINT NOT NULL,
    current_assignee_id BIGINT,
    assigned_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT resource_current_assignee_id_fkey FOREIGN KEY (current_assignee_id) REFERENCES staff(id) ON DELETE SET NULL,
    CONSTRAINT resource_branch_id_resource_number_key UNIQUE (branch_id, resource_number)
);

-- 9. Customer order table
CREATE TABLE IF NOT EXISTS customer_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    order_status order_status NOT NULL DEFAULT 'pending',
    total_amount NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    payment_status payment_status NOT NULL DEFAULT 'unpaid',
    branch_id BIGINT,
    CONSTRAINT customer_order_total_amount_check CHECK (total_amount >= 0::numeric),
    CONSTRAINT customer_order_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE SET NULL
);

-- 10. Order item table
CREATE TABLE IF NOT EXISTS order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    inventory_id BIGINT NOT NULL,
    CONSTRAINT order_item_quantity_check CHECK (quantity > 0),
    CONSTRAINT order_item_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES inventory_item(inventory_id) ON DELETE RESTRICT,
    CONSTRAINT order_item_order_id_fkey FOREIGN KEY (order_id) REFERENCES customer_order(id) ON DELETE CASCADE
);

-- 11. Owner table
CREATE TABLE IF NOT EXISTS owner (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT owner_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE
);

-- 12. Payment table
CREATE TABLE IF NOT EXISTS payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    payment_method TEXT NOT NULL,
    transaction_id TEXT UNIQUE,
    status payment_status NOT NULL DEFAULT 'paid',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT payment_amount_check CHECK (amount >= 0::numeric),
    CONSTRAINT payment_order_id_fkey FOREIGN KEY (order_id) REFERENCES customer_order(id) ON DELETE CASCADE
);

-- 13. Supplier table
CREATE TABLE IF NOT EXISTS supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    supplier_name TEXT NOT NULL,
    supplier_tel TEXT,
    address TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    supplier_email TEXT,
    CONSTRAINT supplier_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE SET NULL
);

-- 14. Supplier item table
CREATE TABLE IF NOT EXISTS supplier_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    item_name TEXT NOT NULL,
    CONSTRAINT supplier_item_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE CASCADE,
    CONSTRAINT supplier_item_supplier_id_item_name_key UNIQUE (supplier_id, item_name)
);

-- 15. Supplier order table
CREATE TABLE IF NOT EXISTS supplier_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT,
    order_status order_status NOT NULL DEFAULT 'pending',
    quantity NUMERIC(12,2) NOT NULL,
    item_price NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    branch_id BIGINT,
    CONSTRAINT supplier_order_item_price_check CHECK (item_price >= 0::numeric),
    CONSTRAINT supplier_order_quantity_check CHECK (quantity > 0::numeric),
    CONSTRAINT supplier_order_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE SET NULL
);

-- 16. Usage history table
CREATE TABLE IF NOT EXISTS usage_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE,
    purpose TEXT,
    resource_id BIGINT NOT NULL,
    CONSTRAINT usage_history_check CHECK ((end_date IS NULL) OR (end_date >= start_date)),
    CONSTRAINT usage_history_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES resource(id) ON DELETE CASCADE
);

-- 17. Notification table
CREATE TABLE IF NOT EXISTS notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT notification_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE
);

-- 18. Staff resource assignment table
CREATE TABLE IF NOT EXISTS staff_resource_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    assigned_by BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT staff_resource_assignment_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES "user"(user_id) ON DELETE SET NULL,
    CONSTRAINT staff_resource_assignment_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES resource(id) ON DELETE CASCADE,
    CONSTRAINT staff_resource_assignment_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE,
    CONSTRAINT staff_resource_assignment_staff_id_resource_id_key UNIQUE (staff_id, resource_id)
);

-- 19. Staff types table
CREATE TABLE IF NOT EXISTS staff_types (
    staff_id BIGINT NOT NULL,
    staff_type VARCHAR(255),
    CONSTRAINT staff_types_staff_type_check CHECK (staff_type::text = ANY (ARRAY['INVENTORY'::character varying, 'SALES'::character varying, 'RESOURCES'::character varying]::text[])),
    CONSTRAINT fke35o60bickknpq1r0y9ddnwy3 FOREIGN KEY (staff_id) REFERENCES staff(id)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_staff_manager_id ON staff(manager_id);
CREATE INDEX IF NOT EXISTS idx_staff_branch_id ON staff(branch_id);
CREATE INDEX IF NOT EXISTS idx_staff_resource_assignment_staff_id ON staff_resource_assignment(staff_id);
CREATE INDEX IF NOT EXISTS idx_staff_resource_assignment_resource_id ON staff_resource_assignment(resource_id);
CREATE INDEX IF NOT EXISTS idx_staff_resource_assignment_active ON staff_resource_assignment(is_active);

-- Insert default roles (matching your application's expectations)
INSERT INTO roles (role, description) VALUES 
('OWNER', 'System administrator with full access'),
('BRANCH_MANAGER', 'Manager of a specific branch'),
('STAFF', 'Branch staff member'),
('SUPPLIER', 'External supplier'),
('CUSTOMER', 'Customer of the business')
ON CONFLICT (role) DO NOTHING;

-- Insert default branch
INSERT INTO branches (name, description, status, created_at) VALUES 
('Default Branch', 'Main branch location', 'ACTIVE', now())
ON CONFLICT (name) DO NOTHING;
