-- Enhanced Resource Management Migration
-- This migration enhances the existing resource management tables to support full functionality

-- Add missing columns to resource table
DO $$ BEGIN
    -- Add description/details field
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'resource' AND column_name = 'description') THEN
        ALTER TABLE resource ADD COLUMN description TEXT;
    END IF;
    
    -- Add resource type/category
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'resource' AND column_name = 'resource_type') THEN
        ALTER TABLE resource ADD COLUMN resource_type VARCHAR(100) DEFAULT 'GENERAL';
    END IF;
    
    -- Add timestamps
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'resource' AND column_name = 'created_at') THEN
        ALTER TABLE resource ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT now();
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'resource' AND column_name = 'updated_at') THEN
        ALTER TABLE resource ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();
    END IF;
    
    -- Add created_by field
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'resource' AND column_name = 'created_by') THEN
        ALTER TABLE resource ADD COLUMN created_by BIGINT REFERENCES "user"(user_id) ON DELETE SET NULL;
    END IF;
END $$;

-- Enhanced staff_resource_assignment table for better assignment tracking
DO $$ BEGIN
    -- Add purpose field
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'staff_resource_assignment' AND column_name = 'purpose') THEN
        ALTER TABLE staff_resource_assignment ADD COLUMN purpose TEXT;
    END IF;
    
    -- Add start and end dates
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'staff_resource_assignment' AND column_name = 'start_date') THEN
        ALTER TABLE staff_resource_assignment ADD COLUMN start_date DATE;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'staff_resource_assignment' AND column_name = 'end_date') THEN
        ALTER TABLE staff_resource_assignment ADD COLUMN end_date DATE;
    END IF;
    
    -- Add start and end times
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'staff_resource_assignment' AND column_name = 'start_time') THEN
        ALTER TABLE staff_resource_assignment ADD COLUMN start_time TIME;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'staff_resource_assignment' AND column_name = 'end_time') THEN
        ALTER TABLE staff_resource_assignment ADD COLUMN end_time TIME;
    END IF;
    
    -- Add unassigned_at field
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'staff_resource_assignment' AND column_name = 'unassigned_at') THEN
        ALTER TABLE staff_resource_assignment ADD COLUMN unassigned_at TIMESTAMP WITH TIME ZONE;
    END IF;
    
    -- Add unassigned_by field
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'staff_resource_assignment' AND column_name = 'unassigned_by') THEN
        ALTER TABLE staff_resource_assignment ADD COLUMN unassigned_by BIGINT REFERENCES "user"(user_id) ON DELETE SET NULL;
    END IF;
END $$;

-- Create resource_types table for better categorization
CREATE TABLE IF NOT EXISTS resource_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Insert default resource types
INSERT INTO resource_types (name, description) VALUES 
('VEHICLE', 'Delivery trucks, vans, cars, and other vehicles'),
('EQUIPMENT', 'Forklifts, machinery, and tools'),
('FACILITY', 'Warehouses, meeting rooms, and spaces'),
('TECHNOLOGY', 'Computers, tablets, and IT equipment'),
('GENERAL', 'Other miscellaneous resources')
ON CONFLICT (name) DO NOTHING;

-- Create a view for easy resource querying with assignment details
CREATE OR REPLACE VIEW resource_with_assignment_view AS
SELECT 
    r.id,
    r.name,
    r.resource_number,
    r.description,
    r.resource_type,
    r.availability_status,
    r.branch_id,
    r.created_at,
    r.updated_at,
    r.created_by,
    
    -- Current assignment details
    sra.id as assignment_id,
    sra.purpose,
    sra.start_date,
    sra.end_date,
    sra.start_time,
    sra.end_time,
    sra.assigned_at,
    
    -- Staff details
    s.id as staff_id,
    s.first_name,
    s.last_name,
    s.email as staff_email,
    s.tel as staff_phone,
    
    -- Branch details
    b.name as branch_name,
    b.location as branch_location
    
FROM resource r
LEFT JOIN staff_resource_assignment sra ON r.id = sra.resource_id AND sra.is_active = true
LEFT JOIN staff s ON sra.staff_id = s.id
LEFT JOIN branches b ON r.branch_id = b.id;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_resource_branch_id ON resource(branch_id);
CREATE INDEX IF NOT EXISTS idx_resource_availability_status ON resource(availability_status);
CREATE INDEX IF NOT EXISTS idx_resource_type ON resource(resource_type);
CREATE INDEX IF NOT EXISTS idx_staff_resource_assignment_dates ON staff_resource_assignment(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_staff_resource_assignment_active ON staff_resource_assignment(is_active);

-- Add triggers for updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger for resource table
DROP TRIGGER IF EXISTS update_resource_updated_at ON resource;
CREATE TRIGGER update_resource_updated_at
    BEFORE UPDATE ON resource
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Update existing resources with default values
UPDATE resource 
SET description = 'Legacy resource - please update description',
    resource_type = 'GENERAL',
    created_at = now(),
    updated_at = now()
WHERE description IS NULL OR resource_type IS NULL OR created_at IS NULL;

-- Add some sample data for testing (optional)
-- INSERT INTO resource (name, resource_number, description, resource_type, availability_status, branch_id)
-- SELECT 
--     'Sample Delivery Truck',
--     'DT-001',
--     'Large delivery truck for cement and bulk materials',
--     'VEHICLE',
--     'available',
--     (SELECT id FROM branches LIMIT 1)
-- WHERE NOT EXISTS (SELECT 1 FROM resource WHERE resource_number = 'DT-001');

COMMENT ON TABLE resource IS 'Stores all company resources including vehicles, equipment, and facilities';
COMMENT ON TABLE staff_resource_assignment IS 'Tracks current and historical assignments of resources to staff members';
COMMENT ON VIEW resource_with_assignment_view IS 'Consolidated view of resources with their current assignment and staff details';
