-- =====================================================
-- Smart Inventory and Resource Management System
-- Database Schema for PostgreSQL
-- =====================================================
-- Generated from NEON database on 2025-08-31
-- 
-- To create a new database with this schema:
-- 1. Create a new PostgreSQL database
-- 2. Run this script in the database
-- 
-- Usage:
-- psql -d your_database_name -f smart_inventory_schema.sql
-- =====================================================

-- Set basic configuration
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;

-- =====================================================
-- CUSTOM TYPES (ENUMS)
-- =====================================================

-- Account status for users
CREATE TYPE account_status AS ENUM (
    'active',
    'inactive',
    'suspended',
    'pending_activation'
);

-- Resource availability status
CREATE TYPE availability_status AS ENUM (
    'available',
    'under_maintenance',
    'used'
);

-- Branch operational status
CREATE TYPE branch_status AS ENUM (
    'active',
    'inactive'
);

-- Order processing status
CREATE TYPE order_status AS ENUM (
    'pending',
    'processing',
    'completed',
    'cancelled'
);

-- Payment status for orders
CREATE TYPE payment_status AS ENUM (
    'paid',
    'unpaid'
);

-- Staff role within the system
CREATE TYPE staff_role AS ENUM (
    'inventory_manager',
    'resource_manager',
    'sales_manager',
    'staff'
);

-- Staff type categorization
CREATE TYPE staff_type AS ENUM (
    'SALES',
    'INVENTORY',
    'RESOURCES'
);

-- =====================================================
-- CORE TABLES
-- =====================================================

-- Roles table for user permissions
CREATE TABLE roles (
    id bigint NOT NULL,
    role character varying(255) NOT NULL,
    description character varying(255)
);

ALTER TABLE roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Users table (main authentication)
CREATE TABLE "user" (
    user_id bigint NOT NULL,
    firebase_uid character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_login timestamp with time zone,
    profile_pic_url character varying(255),
    account_status character varying(255) DEFAULT 'active'::account_status NOT NULL,
    role_id bigint NOT NULL,
    created_by bigint,
    password_hash character varying(255),
    temp_password boolean DEFAULT false,
    is_active boolean NOT NULL
);

ALTER TABLE "user" ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Branches table
CREATE TABLE branches (
    id bigint NOT NULL,
    contact_number character varying(255),
    created_at timestamp(6) without time zone,
    description character varying(255),
    location character varying(255),
    name character varying(255) NOT NULL,
    status character varying(255),
    manager_id bigint,
    owner_id bigint,
    CONSTRAINT branches_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

ALTER TABLE branches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME branches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Staff table
CREATE TABLE staff (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    address character varying(255),
    tel character varying(255),
    branch_id bigint,
    manager_id bigint,
    salary numeric(38,2),
    staff_types text DEFAULT '{}'::staff_type[] NOT NULL,
    hire_date timestamp with time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    CONSTRAINT staff_salary_check CHECK ((salary >= (0)::numeric))
);

ALTER TABLE staff ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME staff_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Owner table
CREATE TABLE owner (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    business_name character varying(255),
    business_registration_number character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE owner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME owner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Customers table
CREATE TABLE customer (
    id bigint NOT NULL,
    user_id bigint,
    customer_name text NOT NULL,
    customer_tel text,
    address text,
    loyalty_points numeric(12,2) DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    customer_email text,
    CONSTRAINT customer_loyalty_points_check CHECK ((loyalty_points >= (0)::numeric))
);

ALTER TABLE customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Categories for inventory items
CREATE TABLE category (
    id bigint NOT NULL,
    category_name text NOT NULL
);

ALTER TABLE category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Inventory items
CREATE TABLE inventory_item (
    inventory_id bigint NOT NULL,
    inventory_name text NOT NULL,
    quantity integer DEFAULT 0 NOT NULL,
    category_id bigint NOT NULL,
    low_stock_threshold integer DEFAULT 0 NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    branch_id bigint NOT NULL,
    CONSTRAINT inventory_item_low_stock_threshold_check CHECK ((low_stock_threshold >= 0)),
    CONSTRAINT inventory_item_quantity_check CHECK ((quantity >= 0)),
    CONSTRAINT inventory_item_unit_price_check CHECK ((unit_price >= (0)::numeric))
);

ALTER TABLE inventory_item ALTER COLUMN inventory_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME inventory_item_inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Resources table
CREATE TABLE resource (
    id bigint NOT NULL,
    resource_name text NOT NULL,
    resource_type text,
    availability_status availability_status DEFAULT 'available'::availability_status NOT NULL,
    maintenance_cost numeric(12,2) DEFAULT 0,
    purchase_date date,
    branch_id bigint NOT NULL,
    CONSTRAINT resource_maintenance_cost_check CHECK ((maintenance_cost >= (0)::numeric))
);

ALTER TABLE resource ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME resource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Customer orders
CREATE TABLE customer_order (
    id bigint NOT NULL,
    customer_id bigint,
    order_status order_status DEFAULT 'pending'::order_status NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    payment_status payment_status DEFAULT 'unpaid'::payment_status NOT NULL,
    branch_id bigint,
    CONSTRAINT customer_order_total_amount_check CHECK ((total_amount >= (0)::numeric))
);

ALTER TABLE customer_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME customer_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Order items (line items for orders)
CREATE TABLE order_item (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    inventory_id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    CONSTRAINT order_item_quantity_check CHECK ((quantity > 0)),
    CONSTRAINT order_item_unit_price_check CHECK ((unit_price >= (0)::numeric))
);

ALTER TABLE order_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Suppliers table
CREATE TABLE supplier (
    id bigint NOT NULL,
    user_id bigint,
    supplier_name text NOT NULL,
    contact_person text,
    supplier_tel text,
    supplier_email text,
    address text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE supplier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME supplier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Supplier items
CREATE TABLE supplier_item (
    id bigint NOT NULL,
    supplier_id bigint NOT NULL,
    inventory_id bigint NOT NULL,
    supplier_price numeric(12,2) NOT NULL,
    CONSTRAINT supplier_item_supplier_price_check CHECK ((supplier_price >= (0)::numeric))
);

ALTER TABLE supplier_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME supplier_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Supplier orders
CREATE TABLE supplier_order (
    id bigint NOT NULL,
    supplier_id bigint NOT NULL,
    inventory_id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    total_price numeric(12,2) NOT NULL,
    order_date timestamp with time zone DEFAULT now() NOT NULL,
    branch_id bigint NOT NULL,
    CONSTRAINT supplier_order_quantity_check CHECK ((quantity > 0)),
    CONSTRAINT supplier_order_total_price_check CHECK ((total_price >= (0)::numeric)),
    CONSTRAINT supplier_order_unit_price_check CHECK ((unit_price >= (0)::numeric))
);

ALTER TABLE supplier_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME supplier_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Notifications
CREATE TABLE notification (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    message text NOT NULL,
    is_read boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    notification_type text DEFAULT 'general'::text NOT NULL
);

ALTER TABLE notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Staff resource assignments
CREATE TABLE staff_resource_assignment (
    id bigint NOT NULL,
    staff_id bigint NOT NULL,
    resource_id bigint NOT NULL,
    assigned_at timestamp with time zone DEFAULT now() NOT NULL,
    released_at timestamp with time zone
);

ALTER TABLE staff_resource_assignment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME staff_resource_assignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Staff types (deprecated - kept for compatibility)
CREATE TABLE staff_types (
    staff_id bigint NOT NULL,
    types character varying(255)
);

-- Usage history for resources
CREATE TABLE usage_history (
    id bigint NOT NULL,
    resource_id bigint NOT NULL,
    staff_id bigint,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone,
    usage_purpose text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE usage_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME usage_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Payments table
CREATE TABLE payment (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    payment_method text NOT NULL,
    amount numeric(12,2) NOT NULL,
    payment_date timestamp with time zone DEFAULT now() NOT NULL,
    payment_status payment_status DEFAULT 'unpaid'::payment_status NOT NULL,
    CONSTRAINT payment_amount_check CHECK ((amount >= (0)::numeric))
);

ALTER TABLE payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- =====================================================
-- PRIMARY KEY CONSTRAINTS
-- =====================================================

ALTER TABLE ONLY branches ADD CONSTRAINT branches_pkey PRIMARY KEY (id);
ALTER TABLE ONLY category ADD CONSTRAINT category_pkey PRIMARY KEY (id);
ALTER TABLE ONLY customer ADD CONSTRAINT customer_pkey PRIMARY KEY (id);
ALTER TABLE ONLY customer_order ADD CONSTRAINT customer_order_pkey PRIMARY KEY (id);
ALTER TABLE ONLY inventory_item ADD CONSTRAINT inventory_item_pkey PRIMARY KEY (inventory_id);
ALTER TABLE ONLY notification ADD CONSTRAINT notification_pkey PRIMARY KEY (id);
ALTER TABLE ONLY order_item ADD CONSTRAINT order_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY owner ADD CONSTRAINT owner_pkey PRIMARY KEY (id);
ALTER TABLE ONLY payment ADD CONSTRAINT payment_pkey PRIMARY KEY (id);
ALTER TABLE ONLY resource ADD CONSTRAINT resource_pkey PRIMARY KEY (id);
ALTER TABLE ONLY roles ADD CONSTRAINT roles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY staff ADD CONSTRAINT staff_pkey PRIMARY KEY (id);
ALTER TABLE ONLY staff_resource_assignment ADD CONSTRAINT staff_resource_assignment_pkey PRIMARY KEY (id);
ALTER TABLE ONLY supplier ADD CONSTRAINT supplier_pkey PRIMARY KEY (id);
ALTER TABLE ONLY supplier_item ADD CONSTRAINT supplier_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY supplier_order ADD CONSTRAINT supplier_order_pkey PRIMARY KEY (id);
ALTER TABLE ONLY usage_history ADD CONSTRAINT usage_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY "user" ADD CONSTRAINT user_pkey PRIMARY KEY (user_id);

-- =====================================================
-- UNIQUE CONSTRAINTS
-- =====================================================

ALTER TABLE ONLY category ADD CONSTRAINT category_category_name_key UNIQUE (category_name);
ALTER TABLE ONLY staff ADD CONSTRAINT staff_email_key UNIQUE (email);
ALTER TABLE ONLY "user" ADD CONSTRAINT user_email_key UNIQUE (email);
ALTER TABLE ONLY "user" ADD CONSTRAINT user_firebase_uid_key UNIQUE (firebase_uid);

-- =====================================================
-- FOREIGN KEY CONSTRAINTS
-- =====================================================

-- Branches relationships
ALTER TABLE ONLY branches ADD CONSTRAINT fk6eeprxgcycf33592pdt128nbq 
    FOREIGN KEY (manager_id) REFERENCES "user"(user_id);
ALTER TABLE ONLY branches ADD CONSTRAINT fk7w3xkxoxlhs4a8t4d5ks58p0p 
    FOREIGN KEY (owner_id) REFERENCES "user"(user_id);

-- Customer relationships
ALTER TABLE ONLY customer ADD CONSTRAINT customer_user_id_fkey 
    FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE SET NULL;

-- Customer order relationships
ALTER TABLE ONLY customer_order ADD CONSTRAINT customer_order_branch_id_fkey 
    FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL;
ALTER TABLE ONLY customer_order ADD CONSTRAINT customer_order_customer_id_fkey 
    FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE SET NULL;

-- Inventory relationships
ALTER TABLE ONLY inventory_item ADD CONSTRAINT fk1lha0ag3td43wl4slo0mnujdq 
    FOREIGN KEY (branch_id) REFERENCES branches(id);
ALTER TABLE ONLY inventory_item ADD CONSTRAINT inventory_item_category_id_fkey 
    FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE RESTRICT;

-- Notification relationships
ALTER TABLE ONLY notification ADD CONSTRAINT notification_user_id_fkey 
    FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE;

-- Order item relationships
ALTER TABLE ONLY order_item ADD CONSTRAINT order_item_inventory_id_fkey 
    FOREIGN KEY (inventory_id) REFERENCES inventory_item(inventory_id) ON DELETE RESTRICT;
ALTER TABLE ONLY order_item ADD CONSTRAINT order_item_order_id_fkey 
    FOREIGN KEY (order_id) REFERENCES customer_order(id) ON DELETE CASCADE;

-- Owner relationships
ALTER TABLE ONLY owner ADD CONSTRAINT owner_user_id_fkey 
    FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE;

-- Payment relationships
ALTER TABLE ONLY payment ADD CONSTRAINT payment_order_id_fkey 
    FOREIGN KEY (order_id) REFERENCES customer_order(id) ON DELETE CASCADE;

-- Resource relationships
ALTER TABLE ONLY resource ADD CONSTRAINT resource_branch_id_fkey 
    FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT;

-- Staff relationships
ALTER TABLE ONLY staff ADD CONSTRAINT staff_branch_id_fkey 
    FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL;
ALTER TABLE ONLY staff ADD CONSTRAINT staff_manager_id_fkey 
    FOREIGN KEY (manager_id) REFERENCES "user"(user_id) ON DELETE SET NULL;
ALTER TABLE ONLY staff ADD CONSTRAINT staff_user_id_fkey 
    FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE;

-- Staff resource assignment relationships
ALTER TABLE ONLY staff_resource_assignment ADD CONSTRAINT staff_resource_assignment_resource_id_fkey 
    FOREIGN KEY (resource_id) REFERENCES resource(id) ON DELETE CASCADE;
ALTER TABLE ONLY staff_resource_assignment ADD CONSTRAINT staff_resource_assignment_staff_id_fkey 
    FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE;

-- Supplier relationships
ALTER TABLE ONLY supplier ADD CONSTRAINT supplier_user_id_fkey 
    FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE SET NULL;

-- Supplier item relationships
ALTER TABLE ONLY supplier_item ADD CONSTRAINT supplier_item_inventory_id_fkey 
    FOREIGN KEY (inventory_id) REFERENCES inventory_item(inventory_id) ON DELETE CASCADE;
ALTER TABLE ONLY supplier_item ADD CONSTRAINT supplier_item_supplier_id_fkey 
    FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE CASCADE;

-- Supplier order relationships
ALTER TABLE ONLY supplier_order ADD CONSTRAINT supplier_order_branch_id_fkey 
    FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT;
ALTER TABLE ONLY supplier_order ADD CONSTRAINT supplier_order_inventory_id_fkey 
    FOREIGN KEY (inventory_id) REFERENCES inventory_item(inventory_id) ON DELETE RESTRICT;
ALTER TABLE ONLY supplier_order ADD CONSTRAINT supplier_order_supplier_id_fkey 
    FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE RESTRICT;

-- Usage history relationships
ALTER TABLE ONLY usage_history ADD CONSTRAINT usage_history_resource_id_fkey 
    FOREIGN KEY (resource_id) REFERENCES resource(id) ON DELETE CASCADE;
ALTER TABLE ONLY usage_history ADD CONSTRAINT usage_history_staff_id_fkey 
    FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE SET NULL;

-- User relationships
ALTER TABLE ONLY "user" ADD CONSTRAINT user_created_by_fkey 
    FOREIGN KEY (created_by) REFERENCES "user"(user_id) ON DELETE SET NULL;
ALTER TABLE ONLY "user" ADD CONSTRAINT user_role_id_fkey 
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT;

-- =====================================================
-- INITIAL DATA (ROLES)
-- =====================================================

-- Insert default roles
INSERT INTO roles (role, description) VALUES 
    ('OWNER', 'System owner with full access'),
    ('BRANCH_MANAGER', 'Branch manager with branch-level access'),
    ('STAFF', 'Staff member with limited access'),
    ('CUSTOMER', 'Customer with shopping access'),
    ('SUPPLIER', 'Supplier with supply-related access');

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================

-- User-related indexes
CREATE INDEX idx_user_firebase_uid ON "user"(firebase_uid);
CREATE INDEX idx_user_email ON "user"(email);
CREATE INDEX idx_user_role_id ON "user"(role_id);

-- Staff-related indexes
CREATE INDEX idx_staff_manager_id ON staff(manager_id);
CREATE INDEX idx_staff_branch_id ON staff(branch_id);
CREATE INDEX idx_staff_user_id ON staff(user_id);

-- Branch-related indexes
CREATE INDEX idx_branches_manager_id ON branches(manager_id);
CREATE INDEX idx_branches_owner_id ON branches(owner_id);

-- Inventory-related indexes
CREATE INDEX idx_inventory_branch_id ON inventory_item(branch_id);
CREATE INDEX idx_inventory_category_id ON inventory_item(category_id);

-- Order-related indexes
CREATE INDEX idx_customer_order_customer_id ON customer_order(customer_id);
CREATE INDEX idx_customer_order_branch_id ON customer_order(branch_id);
CREATE INDEX idx_order_item_order_id ON order_item(order_id);
CREATE INDEX idx_order_item_inventory_id ON order_item(inventory_id);

-- Resource-related indexes
CREATE INDEX idx_resource_branch_id ON resource(branch_id);
CREATE INDEX idx_staff_resource_assignment_staff_id ON staff_resource_assignment(staff_id);
CREATE INDEX idx_staff_resource_assignment_resource_id ON staff_resource_assignment(resource_id);

-- =====================================================
-- COMPLETION MESSAGE
-- =====================================================

-- Schema creation completed successfully
SELECT 'Smart Inventory and Resource Management System schema created successfully!' as message;
