-- SUPPLIER MANAGEMENT DATABASE ENHANCEMENT
-- This file contains the database changes needed for the supplier management system
-- Date: September 5, 2025

-- ========================================
-- STEP 1: CREATE NEW ENUMS (if needed)
-- ========================================

-- Add restock request status enum
DO $$ BEGIN
    CREATE TYPE restock_request_status AS ENUM ('pending', 'active', 'completed', 'cancelled');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$ LANGUAGE plpgsql;

-- Add supplier order payment status enum  
DO $$ BEGIN
    CREATE TYPE supplier_payment_status AS ENUM ('unpaid', 'paid', 'cancelled', 'refunded');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$ LANGUAGE plpgsql;

-- ========================================
-- STEP 2: CREATE NEW TABLES
-- ========================================

-- 1. Restock Request Table (Staff/Branch Manager creates these)
CREATE TABLE IF NOT EXISTS restock_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL, -- Staff/Branch Manager who created the request
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status restock_request_status NOT NULL DEFAULT 'pending',
    total_estimated_cost NUMERIC(12,2) DEFAULT 0,
    priority VARCHAR(20) DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
    required_by_date DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    completed_at TIMESTAMP WITH TIME ZONE,
    notes TEXT,
    
    CONSTRAINT restock_request_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT restock_request_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT restock_request_total_estimated_cost_check CHECK (total_estimated_cost >= 0::numeric)
);

-- 2. Restock Request Items Table (Items in the restock cart)
CREATE TABLE IF NOT EXISTS restock_request_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restock_request_id BIGINT NOT NULL,
    inventory_id BIGINT NOT NULL, -- Reference to inventory_item
    requested_quantity INTEGER NOT NULL,
    estimated_unit_price NUMERIC(12,2), -- Estimated price for budgeting
    notes TEXT, -- Special requirements for this item
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    
    CONSTRAINT restock_request_item_restock_request_id_fkey FOREIGN KEY (restock_request_id) REFERENCES restock_request(id) ON DELETE CASCADE,
    CONSTRAINT restock_request_item_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES inventory_item(inventory_id) ON DELETE CASCADE,
    CONSTRAINT restock_request_item_requested_quantity_check CHECK (requested_quantity > 0),
    CONSTRAINT restock_request_item_estimated_unit_price_check CHECK (estimated_unit_price >= 0::numeric),
    CONSTRAINT restock_request_item_unique UNIQUE (restock_request_id, inventory_id)
);

-- ========================================
-- STEP 3: ENHANCE EXISTING SUPPLIER TABLES
-- ========================================

-- Drop the current supplier_order table to recreate it with proper structure
DROP TABLE IF EXISTS supplier_order CASCADE;

-- Enhanced Supplier Order Table (Suppliers create these in response to restock requests)
CREATE TABLE IF NOT EXISTS supplier_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restock_request_id BIGINT NOT NULL, -- Links to the restock request
    supplier_id BIGINT NOT NULL,
    order_status order_status NOT NULL DEFAULT 'pending',
    payment_status supplier_payment_status NOT NULL DEFAULT 'unpaid',
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    estimated_delivery_date DATE,
    actual_delivery_date DATE,
    supplier_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    paid_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    
    -- Payment integration fields
    stripe_payment_intent_id VARCHAR(255),
    payment_method VARCHAR(50) DEFAULT 'stripe',
    
    CONSTRAINT supplier_order_restock_request_id_fkey FOREIGN KEY (restock_request_id) REFERENCES restock_request(id) ON DELETE CASCADE,
    CONSTRAINT supplier_order_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE CASCADE,
    CONSTRAINT supplier_order_total_amount_check CHECK (total_amount >= 0::numeric)
);

-- 3. Supplier Order Items Table (Individual items in supplier orders with pricing)
CREATE TABLE IF NOT EXISTS supplier_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_order_id BIGINT NOT NULL,
    restock_request_item_id BIGINT NOT NULL, -- Links to the specific requested item
    inventory_id BIGINT NOT NULL, -- Reference to inventory_item
    supplier_item_name VARCHAR(255), -- Supplier's name for the item (might differ)
    offered_quantity INTEGER NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    total_price NUMERIC(12,2) NOT NULL,
    supplier_item_description TEXT,
    availability_status VARCHAR(50) DEFAULT 'available' CHECK (availability_status IN ('available', 'limited', 'out_of_stock', 'discontinued')),
    lead_time_days INTEGER DEFAULT 0,
    
    CONSTRAINT supplier_order_item_supplier_order_id_fkey FOREIGN KEY (supplier_order_id) REFERENCES supplier_order(id) ON DELETE CASCADE,
    CONSTRAINT supplier_order_item_restock_request_item_id_fkey FOREIGN KEY (restock_request_item_id) REFERENCES restock_request_item(id) ON DELETE CASCADE,
    CONSTRAINT supplier_order_item_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES inventory_item(inventory_id) ON DELETE CASCADE,
    CONSTRAINT supplier_order_item_offered_quantity_check CHECK (offered_quantity > 0),
    CONSTRAINT supplier_order_item_unit_price_check CHECK (unit_price >= 0::numeric),
    CONSTRAINT supplier_order_item_total_price_check CHECK (total_price >= 0::numeric),
    CONSTRAINT supplier_order_item_lead_time_check CHECK (lead_time_days >= 0),
    CONSTRAINT supplier_order_item_unique UNIQUE (supplier_order_id, restock_request_item_id)
);

-- 4. Enhance supplier_item table to include capabilities
DROP TABLE IF EXISTS supplier_item CASCADE;

CREATE TABLE IF NOT EXISTS supplier_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    inventory_id BIGINT, -- Link to specific inventory items they can supply
    supplier_item_name VARCHAR(255) NOT NULL, -- Supplier's name for the item
    category_id BIGINT, -- Category they specialize in
    base_unit_price NUMERIC(12,2), -- Their standard price
    minimum_order_quantity INTEGER DEFAULT 1,
    maximum_order_quantity INTEGER,
    lead_time_days INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    
    CONSTRAINT supplier_item_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE CASCADE,
    CONSTRAINT supplier_item_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES inventory_item(inventory_id) ON DELETE SET NULL,
    CONSTRAINT supplier_item_category_id_fkey FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE SET NULL,
    CONSTRAINT supplier_item_base_unit_price_check CHECK (base_unit_price >= 0::numeric),
    CONSTRAINT supplier_item_minimum_order_quantity_check CHECK (minimum_order_quantity > 0),
    CONSTRAINT supplier_item_maximum_order_quantity_check CHECK (maximum_order_quantity IS NULL OR maximum_order_quantity >= minimum_order_quantity),
    CONSTRAINT supplier_item_lead_time_check CHECK (lead_time_days >= 0)
);

-- 5. Supplier Payment Table (Track payments to suppliers)
CREATE TABLE IF NOT EXISTS supplier_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_order_id BIGINT NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    payment_method VARCHAR(50) DEFAULT 'stripe',
    stripe_payment_intent_id VARCHAR(255),
    stripe_charge_id VARCHAR(255),
    payment_status supplier_payment_status NOT NULL DEFAULT 'unpaid',
    processed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    metadata JSONB,
    transaction_id TEXT UNIQUE,
    
    CONSTRAINT supplier_payment_supplier_order_id_fkey FOREIGN KEY (supplier_order_id) REFERENCES supplier_order(id) ON DELETE CASCADE,
    CONSTRAINT supplier_payment_amount_check CHECK (amount >= 0::numeric)
);

-- ========================================
-- STEP 4: CREATE INDEXES FOR PERFORMANCE
-- ========================================

-- Restock request indexes
CREATE INDEX IF NOT EXISTS idx_restock_request_branch_id ON restock_request(branch_id);
CREATE INDEX IF NOT EXISTS idx_restock_request_created_by ON restock_request(created_by);
CREATE INDEX IF NOT EXISTS idx_restock_request_status ON restock_request(status);
CREATE INDEX IF NOT EXISTS idx_restock_request_created_at ON restock_request(created_at);
CREATE INDEX IF NOT EXISTS idx_restock_request_priority ON restock_request(priority);

-- Restock request item indexes
CREATE INDEX IF NOT EXISTS idx_restock_request_item_restock_request_id ON restock_request_item(restock_request_id);
CREATE INDEX IF NOT EXISTS idx_restock_request_item_inventory_id ON restock_request_item(inventory_id);

-- Supplier order indexes
CREATE INDEX IF NOT EXISTS idx_supplier_order_restock_request_id ON supplier_order(restock_request_id);
CREATE INDEX IF NOT EXISTS idx_supplier_order_supplier_id ON supplier_order(supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_order_order_status ON supplier_order(order_status);
CREATE INDEX IF NOT EXISTS idx_supplier_order_payment_status ON supplier_order(payment_status);
CREATE INDEX IF NOT EXISTS idx_supplier_order_created_at ON supplier_order(created_at);
CREATE INDEX IF NOT EXISTS idx_supplier_order_stripe_intent ON supplier_order(stripe_payment_intent_id);

-- Supplier order item indexes
CREATE INDEX IF NOT EXISTS idx_supplier_order_item_supplier_order_id ON supplier_order_item(supplier_order_id);
CREATE INDEX IF NOT EXISTS idx_supplier_order_item_restock_request_item_id ON supplier_order_item(restock_request_item_id);
CREATE INDEX IF NOT EXISTS idx_supplier_order_item_inventory_id ON supplier_order_item(inventory_id);

-- Enhanced supplier item indexes
CREATE INDEX IF NOT EXISTS idx_supplier_item_supplier_id ON supplier_item(supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_item_inventory_id ON supplier_item(inventory_id);
CREATE INDEX IF NOT EXISTS idx_supplier_item_category_id ON supplier_item(category_id);
CREATE INDEX IF NOT EXISTS idx_supplier_item_is_active ON supplier_item(is_active);

-- Supplier payment indexes
CREATE INDEX IF NOT EXISTS idx_supplier_payment_supplier_order_id ON supplier_payment(supplier_order_id);
CREATE INDEX IF NOT EXISTS idx_supplier_payment_payment_status ON supplier_payment(payment_status);
CREATE INDEX IF NOT EXISTS idx_supplier_payment_stripe_intent ON supplier_payment(stripe_payment_intent_id);

-- ========================================
-- STEP 5: CREATE VIEWS FOR COMPLEX QUERIES
-- ========================================

-- Restock request summary view
CREATE OR REPLACE VIEW restock_request_summary_view AS
SELECT 
    rr.id as request_id,
    rr.title,
    rr.status,
    rr.priority,
    rr.created_at,
    rr.required_by_date,
    rr.total_estimated_cost,
    
    -- Branch details
    b.name as branch_name,
    b.location as branch_location,
    
    -- Creator details
    u.name as created_by_name,
    u.email as created_by_email,
    
    -- Request statistics
    COUNT(rri.id) as total_items_requested,
    SUM(rri.requested_quantity) as total_quantity_requested,
    COUNT(DISTINCT so.id) as supplier_orders_count,
    COUNT(CASE WHEN so.payment_status = 'paid' THEN 1 END) as paid_orders_count,
    SUM(CASE WHEN so.payment_status = 'paid' THEN so.total_amount ELSE 0 END) as total_paid_amount
    
FROM restock_request rr
LEFT JOIN branches b ON rr.branch_id = b.id
LEFT JOIN "user" u ON rr.created_by = u.user_id
LEFT JOIN restock_request_item rri ON rr.id = rri.restock_request_id
LEFT JOIN supplier_order so ON rr.id = so.restock_request_id
GROUP BY rr.id, rr.title, rr.status, rr.priority, rr.created_at, rr.required_by_date, rr.total_estimated_cost, b.name, b.location, u.name, u.email;

-- Supplier order details view
CREATE OR REPLACE VIEW supplier_order_details_view AS
SELECT 
    so.id as order_id,
    so.order_status,
    so.payment_status,
    so.total_amount,
    so.created_at,
    so.estimated_delivery_date,
    so.actual_delivery_date,
    
    -- Restock request details
    rr.id as request_id,
    rr.title as request_title,
    rr.priority as request_priority,
    
    -- Branch details
    b.name as branch_name,
    b.location as branch_location,
    
    -- Supplier details
    s.supplier_name,
    s.supplier_email,
    s.supplier_tel,
    
    -- Order statistics
    COUNT(soi.id) as items_count,
    SUM(soi.offered_quantity) as total_quantity_offered
    
FROM supplier_order so
LEFT JOIN restock_request rr ON so.restock_request_id = rr.id
LEFT JOIN branches b ON rr.branch_id = b.id
LEFT JOIN supplier s ON so.supplier_id = s.id
LEFT JOIN supplier_order_item soi ON so.id = soi.supplier_order_id
GROUP BY so.id, so.order_status, so.payment_status, so.total_amount, so.created_at, so.estimated_delivery_date, so.actual_delivery_date, rr.id, rr.title, rr.priority, b.name, b.location, s.supplier_name, s.supplier_email, s.supplier_tel;

-- Inventory restock tracking view
CREATE OR REPLACE VIEW inventory_restock_tracking_view AS
SELECT 
    ii.inventory_id,
    ii.inventory_name,
    ii.quantity as current_stock,
    ii.low_stock_threshold,
    
    -- Branch details
    b.name as branch_name,
    
    -- Category details
    c.category_name,
    
    -- Active restock requests for this item
    COUNT(DISTINCT rri.restock_request_id) as active_restock_requests,
    SUM(rri.requested_quantity) as total_requested_quantity,
    
    -- Supplier orders for this item
    COUNT(DISTINCT soi.supplier_order_id) as supplier_orders_count,
    SUM(CASE WHEN so.payment_status = 'paid' THEN soi.offered_quantity ELSE 0 END) as paid_incoming_quantity,
    SUM(CASE WHEN so.order_status = 'pending' AND so.payment_status = 'unpaid' THEN soi.offered_quantity ELSE 0 END) as pending_incoming_quantity
    
FROM inventory_item ii
LEFT JOIN branches b ON ii.branch_id = b.id
LEFT JOIN category c ON ii.category_id = c.id
LEFT JOIN restock_request_item rri ON ii.inventory_id = rri.inventory_id
LEFT JOIN restock_request rr ON rri.restock_request_id = rr.id AND rr.status IN ('pending', 'active')
LEFT JOIN supplier_order_item soi ON rri.id = soi.restock_request_item_id
LEFT JOIN supplier_order so ON soi.supplier_order_id = so.id
GROUP BY ii.inventory_id, ii.inventory_name, ii.quantity, ii.low_stock_threshold, b.name, c.category_name;

-- ========================================
-- STEP 6: CREATE TRIGGERS AND FUNCTIONS
-- ========================================

-- Function to update supplier order total when items change
CREATE OR REPLACE FUNCTION update_supplier_order_total()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE supplier_order 
    SET total_amount = (
        SELECT COALESCE(SUM(total_price), 0)
        FROM supplier_order_item 
        WHERE supplier_order_id = COALESCE(NEW.supplier_order_id, OLD.supplier_order_id)
    ),
    updated_at = now()
    WHERE id = COALESCE(NEW.supplier_order_id, OLD.supplier_order_id);
    
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- Trigger for supplier order items
DROP TRIGGER IF EXISTS trigger_update_supplier_order_total ON supplier_order_item;
CREATE TRIGGER trigger_update_supplier_order_total
    AFTER INSERT OR UPDATE OR DELETE ON supplier_order_item
    FOR EACH ROW
    EXECUTE FUNCTION update_supplier_order_total();

-- Function to update restock request estimated cost
CREATE OR REPLACE FUNCTION update_restock_request_estimated_cost()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE restock_request 
    SET total_estimated_cost = (
        SELECT COALESCE(SUM(requested_quantity * COALESCE(estimated_unit_price, 0)), 0)
        FROM restock_request_item 
        WHERE restock_request_id = COALESCE(NEW.restock_request_id, OLD.restock_request_id)
    ),
    updated_at = now()
    WHERE id = COALESCE(NEW.restock_request_id, OLD.restock_request_id);
    
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- Trigger for restock request items
DROP TRIGGER IF EXISTS trigger_update_restock_request_estimated_cost ON restock_request_item;
CREATE TRIGGER trigger_update_restock_request_estimated_cost
    AFTER INSERT OR UPDATE OR DELETE ON restock_request_item
    FOR EACH ROW
    EXECUTE FUNCTION update_restock_request_estimated_cost();

-- Function to update inventory after successful supplier payment
CREATE OR REPLACE FUNCTION update_inventory_after_supplier_payment()
RETURNS TRIGGER AS $$
BEGIN
    -- Only update inventory when payment status changes to 'paid'
    IF NEW.payment_status = 'paid' AND OLD.payment_status != 'paid' THEN
        -- Update inventory quantities for all items in this supplier order
        UPDATE inventory_item 
        SET quantity = quantity + soi.offered_quantity
        FROM supplier_order_item soi
        WHERE soi.supplier_order_id = NEW.id 
        AND inventory_item.inventory_id = soi.inventory_id;
        
        -- Update the payment timestamp
        NEW.paid_at = now();
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for supplier order payment updates
DROP TRIGGER IF EXISTS trigger_update_inventory_after_supplier_payment ON supplier_order;
CREATE TRIGGER trigger_update_inventory_after_supplier_payment
    BEFORE UPDATE ON supplier_order
    FOR EACH ROW
    EXECUTE FUNCTION update_inventory_after_supplier_payment();

-- ========================================
-- STEP 7: ADD COMMENTS FOR DOCUMENTATION
-- ========================================

-- Table comments
COMMENT ON TABLE restock_request IS 'Restock requests created by staff/branch managers for inventory replenishment';
COMMENT ON TABLE restock_request_item IS 'Individual items requested in a restock request with quantities and estimated prices';
COMMENT ON TABLE supplier_order IS 'Orders created by suppliers in response to restock requests with their pricing';
COMMENT ON TABLE supplier_order_item IS 'Individual items in supplier orders with supplier pricing and availability';
COMMENT ON TABLE supplier_item IS 'Items that suppliers can provide with their capabilities and pricing';
COMMENT ON TABLE supplier_payment IS 'Payment records for supplier orders';

-- Column comments
COMMENT ON COLUMN restock_request.status IS 'Status: pending (draft), active (published to suppliers), completed (all needed items obtained), cancelled';
COMMENT ON COLUMN restock_request.priority IS 'Priority level: low, normal, high, urgent';
COMMENT ON COLUMN restock_request.required_by_date IS 'Date when the restocked items are needed';
COMMENT ON COLUMN supplier_order.payment_status IS 'Payment status: unpaid, paid, cancelled, refunded';
COMMENT ON COLUMN supplier_order_item.availability_status IS 'Supplier item availability: available, limited, out_of_stock, discontinued';
COMMENT ON COLUMN supplier_order_item.lead_time_days IS 'Days needed for supplier to deliver this item';

-- View comments
COMMENT ON VIEW restock_request_summary_view IS 'Summary view of restock requests with statistics and related information';
COMMENT ON VIEW supplier_order_details_view IS 'Detailed view of supplier orders with related request and supplier information';
COMMENT ON VIEW inventory_restock_tracking_view IS 'Tracking view for inventory items showing current stock and incoming quantities';

-- ========================================
-- STEP 8: INSERT SAMPLE DATA (OPTIONAL)
-- ========================================

-- Sample restock request statuses and priorities are already defined in the enums above
-- The triggers will automatically maintain calculated fields

-- Success message
SELECT 'SUPPLIER MANAGEMENT DATABASE ENHANCEMENT COMPLETED!' AS status;
SELECT 'Ready to implement the supplier management workflow.' AS next_step;
