spring.application.name=inventoryAPI

# Postgres connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smart_inventory_resource_management}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Ra#A1381}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Kafka (your existing default is fine)
spring.kafka.bootstrap-servers=${SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS:kafka:9092}


spring.jpa.open-in-view=false
branch.service.base-url: http://branch-service:8081

# --- Resilience4j Retry (branchApi) ---
resilience4j.retry.instances.branchApi.max-attempts=3
resilience4j.retry.instances.branchApi.wait-duration=200ms
resilience4j.retry.instances.branchApi.retry-exceptions[0]=org.springframework.web.reactive.function.client.WebClientRequestException
resilience4j.retry.instances.branchApi.retry-exceptions[1]=java.io.IOException

# --- Resilience4j Circuit Breaker (branchApi) ---
resilience4j.circuitbreaker.instances.branchApi.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.branchApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.branchApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.branchApi.wait-duration-in-open-state=10s
# (optional but useful)
resilience4j.circuitbreaker.instances.branchApi.permitted-number-of-calls-in-half-open-state=3
