spring.application.name=inventoryAPI

spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Kafka (your existing default is fine)
spring.kafka.bootstrap-servers=${SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS:kafka:9092}


spring.jpa.open-in-view=false
branch.service.base-url: http://branch-service:8081

# --- Resilience4j Retry (branchApi) ---
resilience4j.retry.instances.branchApi.max-attempts=3
resilience4j.retry.instances.branchApi.wait-duration=200ms
resilience4j.retry.instances.branchApi.retry-exceptions[0]=org.springframework.web.reactive.function.client.WebClientRequestException
resilience4j.retry.instances.branchApi.retry-exceptions[1]=java.io.IOException

# --- Resilience4j Circuit Breaker (branchApi) ---
resilience4j.circuitbreaker.instances.branchApi.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.branchApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.branchApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.branchApi.wait-duration-in-open-state=10s
# (optional but useful)
resilience4j.circuitbreaker.instances.branchApi.permitted-number-of-calls-in-half-open-state=3