export const INVENTORY_CONSTANTS = {
  colors: {
    primary: "#3674B5",
    success: "#10B981",
    warning: "#F59E0B",
    error: "#EF4444",
    info: "#3B82F6",
  },
  messages: {
    pageTitle: "Inventory Management",
    pageSubtitle: "Track and manage your product inventory",
    addItem: "Add Item",
    addNewItem: "Add New Item",
    editItem: "Edit Item",
    viewItem: "View Item Details",
    deleteItem: "Delete Item",
    searchPlaceholder: "Search inventory items...",
    allCategories: "All Categories",
    noResults: "No inventory items found",
    noResultsDesc: "Try adjusting your search or filters",
    loading: "Loading inventory...",
    saving: "Saving...",
    deleting: "Deleting...",
    confirmDelete: "Are you sure you want to delete this item?",
    deleteWarning: "This action cannot be undone.",
  },
  labels: {
    itemName: "Item Name",
    category: "Category",
    sku: "SKU",
    quantity: "Quantity",
    unit: "Unit",
    expiryDate: "Expiry Date",
    costPrice: "Cost Price",
    sellingPrice: "Selling Price",
    actions: "Actions",
    filters: "Filters",
    search: "Search",
    listView: "List View",
    gridView: "Grid View",
    totalItems: "Total Items",
    totalValue: "Total Value",
    lowStock: "Low Stock Items",
    nearExpiry: "Near Expiry",
  },
  validation: {
    nameRequired: "Item name is required",
    categoryRequired: "Category is required",
    skuRequired: "SKU is required",
    quantityRequired: "Quantity is required",
    quantityMin: "Quantity must be greater than 0",
    unitRequired: "Unit is required",
    expiryRequired: "Expiry date is required",
    costPriceRequired: "Cost price is required",
    costPriceMin: "Cost price must be greater than 0",
    sellingPriceRequired: "Selling price is required",
    sellingPriceMin: "Selling price must be greater than 0",
  },
  defaults: {
    categories: [
      { id: 1, name: "Cement" },
      { id: 2, name: "Nails" },
      { id: 3, name: "Wires" },
      { id: 4, name: "Tools" },
      { id: 5, name: "Pipes" },
      { id: 6, name: "Screws" },
      { id: 7, name: "Paint" },
      { id: 8, name: "Wood" },
    ],
    units: [
      { id: 1, name: "kg" },
      { id: 2, name: "g" },
      { id: 3, name: "m" },
      { id: 4, name: "cm" },
      { id: 5, name: "mm" },
      { id: 6, name: "L" },
      { id: 7, name: "ml" },
      { id: 8, name: "pcs" },
      { id: 9, name: "box" },
      { id: 10, name: "pack" },
    ],
  },
} as const;
