server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:customer-service;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
# application.yml
branch:
  service:
    base-url: http://branch-service:8080   # or the actual URL

resilience4j:
  retry:
    instances:
      branchApi:
        maxAttempts: 3
        waitDuration: 200ms
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.io.IOException
  circuitbreaker:
    instances:
      branchApi:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
