spring.application.name=notificationAPI
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port=8081

# Kafka Configuration
spring.kafka.consumer.bootstrap-servers=localhost:29092
spring.kafka.producer.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

# Email Configuration (Use Gmail SMTP or your SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nimashmanawa2002@gmail.com
spring.mail.password='wyet mxji xoas qhhu'
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
