export const MANAGER_CONSTANTS = {
  colors: {
    primary: "#3674B5",
    success: "#10B981",
    error: "#EF4444",
    warning: "#F59E0B",
  },
  messages: {
    pageTitle: "Create Manager",
    pageSubtitle: "Add a new manager to manage this branch",
    invalidParams: "Invalid Parameters",
    invalidParamsDesc: "Branch information is required to create a manager",
    createSuccess: "Manager Created Successfully!",
    createSuccessDesc:
      "The manager account has been created and they can now log in.",
    createError: "Failed to Create Manager",
    createErrorDesc:
      "There was an error creating the manager account. Please try again.",
    redirecting: "Redirecting to branches...",
    creating: "Creating Manager...",
    generateRandom: "Generate Random",
    cancel: "Cancel",
    createManager: "Create Manager",
  },
  labels: {
    branchInfo: "Branch Information",
    managerDetails: "Manager Details",
    email: "Email Address",
    firstName: "First Name",
    lastName: "Last Name",
    password: "Password",
    confirmPassword: "Confirm Password",
    phoneNumber: "Phone Number",
    address: "Address",
    requiredField: "*",
    optional: "(optional)",
  },
  placeholders: {
    email: "Enter manager's email address",
    firstName: "Enter first name",
    lastName: "Enter last name",
    password: "Enter a secure password (min 6 characters)",
    confirmPassword: "Confirm the password",
    phoneNumber: "Enter phone number (optional)",
    address: "Enter address (optional)",
  },
  validation: {
    emailRequired: "Email is required",
    emailInvalid: "Please enter a valid email address",
    firstNameRequired: "First name is required",
    lastNameRequired: "Last name is required",
    passwordRequired: "Password is required",
    passwordMinLength: "Password must be at least 6 characters long",
    passwordMismatch: "Passwords do not match",
  },
  info: {
    title: "Important Information:",
    points: [
      "The manager will be automatically assigned to this branch",
      "They will receive BRANCH_MANAGER role permissions",
      "Share the password securely with the new manager",
      "The manager should change their password on first login",
      "Only owners can create and manage branch managers",
    ],
  },
} as const;
