spring.application.name=user-roleManagementAPI

server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/user_role_management?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Ra#A1381
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# Keycloak Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8083/realms/myrealm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8083/realms/myrealm/protocol/openid-connect/certs


# Keycloak Admin Client Configuration
keycloak.server-url=http://localhost:8083
keycloak.realm=myrealm
keycloak.admin-username=admin
keycloak.admin-password=admin
keycloak.client-id=springboot-app
keycloak.client-secret=ks631jXyyFXo7sFAl7vxiyk4SmbgQ68S

# Application specific configuration
app.keycloak.realm=myrealm
app.keycloak.client-id=springboot-app
app.keycloak.client-secret=ks631jXyyFXo7sFAl7vxiyk4SmbgQ68S
app.keycloak.server-url=http://localhost:8083

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

logging.level.org.springframework.security=DEBUG
logging.level.org.keycloak=DEBUG
logging.level.org.springframework=INFO